package com.cs.loadbalancer.indesign.bo;

/**
 * @author manini
 *
 */
public enum InDesignRequestResponseStatus {

	RECEIVED_FROM_WEBSERVER,
	PING_FROM_LOADBALANCER,
	WAITING_FOR_INDS, 
	NOTIFIED_FOR_INDS,
	GOT_INDS, 
	SENDING_TO_INDS, 
	NO_INDS_AVAILABLE_SENDING_ERROR_TO_WEBSERVER,
	ERROR_SENDING_TO_INDS_GETTING_NEW_INDS,
	ERROR_IN_REQUEST_PROCESSING,
	SERVER_BUSY,
	RECEIVED_FROM_INDS,
	NOTIFIED_OTHERS_FOR_INDS,
	SUCCESS_FROM_INDS,
	ERROR_FROM_INDS,
	FAULT_FROM_INDS,
	SENT_TO_WEBSERVER;
	

}
